ame: Build M23

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out
      uses: actions/checkout@v2

    - name: Setup SSH Keys
      if: ${{ startsWith(github.event.inputs.MANIFEST_URL, 'git@github.com') }}
      uses: webfactory/ssh-agent@v0.5.4
      with:
          ssh-private-key: |
              ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Initialize repo
      run: |
        git config --global user.name "Nico170420"
        git config --global user.email "b170420nc@gmail.com"

    - name: Create Zip Archive
      run: |
        ZIP_FILE="M23-Hidden_Mods.zip"
        
        cd $GITHUB_WORKSPACE
        
        zip -r $ZIP_FILE .

    - name: Upload to Release
      id: upload-release
      uses: softprops/action-gh-release@v1
      with:
        files: M23-Hidden_Mods.zip
        name: ${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
          Mod Version 1.0
          Device: m23xq
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
