name: Build Hidden-Mods

on:
  workflow_dispatch:
  push:
    branches:
      - A14_1

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      actions: write
    steps:
 
    # You might want to Checkout your repo first, but not mandatory
    - name: Check Out
      uses: actions/checkout@v4

    - name: Create A14_1 Zip Full Archive
      run: |
       git clone https://github.com/Aflaungos/M23-Hidden-Mods -b A14_1 A14_1HM
       cd $GITHUB_WORKSPACE/A14_1HM

       # Hidden-Mods Full
       zip -r M23-Hidden_Mods_A14_1_FULL.zip . -x ".git*" -x ".github*" -x "floating_feature_lite.xml" -x "addon*" -x "MagiskMod.jpg" -x "LICENSE" -x "README.md"

    - name: Create A14_1 Zip Lite Archive
      run: |  
       # Hidden-Mods Lite
       cd $GITHUB_WORKSPACE/A14_1HM/system/etc
       mv floating_feature_lite.xml floating_feature.xml
       cd ..
       cd /app
       rm -rf SmartCapture
       rm -rf VisualCloudCore
       cd ..
       cd /etc
       rm -rf ailasso
       rm -rf inpainting
       rm -rf objectremoval
       rm -rf reflectionremoval
       rm -rf shadowremoval
       rm -rf style_transfer
       cd ..
       rm -rf lib64
       rm -rf vendor
       cd /priv-app
       rm -rf Applock
       rm -rf PetService
       rm -rf PhotoEditor_AIFull
       rm -rf PhotoEditor_Mid
       rm -rf PhotoRemasterService
       rm -rf SpriteWallpaper
       rm -rf TencentWifiSecurity
       rm -rf WallpaperMagician-Stub
       zip -r M23-Hidden_Mods_A14_1_Lite.zip . -x ".git*" -x ".github*" -x "floating_feature.xml" -x "addon*" -x "MagiskMod.jpg" -x "LICENSE" -x "README.md"
       
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          A14_1HM/M23-Hidden_Mods_A14_1_FULL.zip
          A14_1HM/M23-Hidden_Mods_A14_1_Lite.zip
        name: M23 Hidden Mods
        tag_name: ${{ github.run_id }}
        body: |
          Device: Samsung Galaxy M23/F23 5G
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete older releases
      uses: dev-drprasad/delete-older-releases@v0.2.1
      with:
        keep_latest: 1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
